package registry

// GetDefaultProfileTemplate returns the default profile template
func GetDefaultProfileTemplate() string {
	return `---
name: default
description: "Default directives.md template with basic structure"
---

# Agent Instructions

*Generated by agmd - <https://github.com/GluonGrid/agmd>*

:::use guide:agmd

## Project Rules

## Workflows

## Custom Instructions

Add your project-specific instructions, setup notes, and context here.
`
}

// GetDefaultDirectivesTemplate returns the fallback template when no profile is found
func GetDefaultDirectivesTemplate() string {
	return GetDefaultProfileTemplate()
}

// GetAgmdGuideTemplate returns the agmd guide that teaches AI how to use agmd
func GetAgmdGuideTemplate() string {
	return `---
name: agmd
description: "Guide for AI assistants on how to use agmd directives"
---

## agmd Quick Reference

This project uses **agmd** to manage AI instructions. The source file is ` + "`directives.md`" + ` and it generates ` + "`AGENTS.md`" + `.

### Directive Syntax

` + "```" + `markdown
:::use type:name         # Include a single item from ~/.agmd/type/name.md
:::list                  # Include multiple items (mixed types)
rule:typescript
workflow:commit
:::end
:::new type:name         # Define inline content (promote to registry later)
content here...
:::end
:::docs                  # Expand linked docs (managed by agmd doc link/unlink)
svelte-kit
typescript
:::end
:::skills                # Expand linked skills (managed by agmd skill link/unlink)
managing-agmd
:::end
` + "```" + `

### Commands for AI Assistants

` + "```" + `bash
# Read content (no editor)
agmd show type:name              # Display item content
agmd show type:name --raw        # Include frontmatter
agmd file show script.sh         # Show raw file content
agmd doc show my-docs            # Show documentation folder contents

# Create items (no editor)
agmd new type:name --no-editor
agmd new type:name --content "# Content here"
agmd new type:name --local       # Create in project-local .agmd/ (team-shared)
echo "Content" | agmd new type:name
agmd file new script.sh --content "#!/bin/bash"

# Update items (no editor)
agmd edit type:name --content "# New content"
echo "Content" | agmd edit type:name

# Move items between registries
agmd mv rule:my-rule --to-global  # local → global
agmd mv rule:my-rule --to-local   # global → local

# Other commands
agmd sync                        # Generate AGENTS.md from directives.md
agmd list                        # List all registry items (local + global annotated)
agmd promote --all               # Promote all :::new blocks to registry

# Migrating existing projects
agmd migrate CLAUDE.md           # Migrate raw/unstructured file → directives.md
agmd migrate CLAUDE.md --force   # Overwrite existing directives.md
agmd collect                     # Collect rules from agmd project into ~/.agmd/
agmd collect -f CLAUDE.md        # Collect from a specific output file

# Symlinking output to AI-specific files
agmd symlink                     # Interactive: choose target (CLAUDE.md, .cursorrules, etc.)
agmd symlink --target claude     # Symlink AGENTS.md → CLAUDE.md
agmd symlink --target cursor     # Symlink AGENTS.md → .cursorrules
agmd symlink --list              # Show available symlink targets

# Task management
agmd task list                   # List tasks for current project
agmd task list --tree            # Tree view grouped by feature
agmd task list --type bug --priority 0   # Filter: critical bugs only
agmd task list --feature auth    # Filter by feature
agmd task list --status ready    # Filter by status
agmd task new setup-db --content "Set up database"
agmd task new fix-auth -t bug -p 0 --feature auth --content "Critical auth bug"
agmd task new api --blocked-by setup-db  # With dependency
agmd task status setup-db completed
agmd task edit setup-db --priority 1 --type feature
agmd task blocked-by api setup-db   # Add dependency
agmd task unblock api setup-db      # Remove dependency
agmd task clean                  # Delete all completed tasks
agmd task show --all             # Show all tasks with content

# File management (raw files without markdown processing)
agmd file list                   # List all files
agmd file add ./script.sh        # Add existing file to registry
agmd file delete script.sh       # Delete file

# Documentation folders (symlinked into projects)
agmd doc list                    # List all documentation
agmd doc add ./docs my-docs      # Add docs folder to registry
agmd doc link my-docs            # Symlink into project as docs/my-docs
agmd doc unlink my-docs          # Remove symlink

# Agent Skills (https://agentskills.io)
agmd skill install owner/repo    # Install skill from GitHub
agmd skill install owner/repo/subdir --name my-skill
agmd skill list                  # List installed skills (local/global annotated)
agmd skill show my-skill         # Show SKILL.md content
agmd skill link my-skill         # Symlink into .claude/skills/ or .agents/skills/
agmd skill link my-skill --target both  # Link into both
agmd skill unlink my-skill       # Remove symlinks
agmd skill update my-skill       # Re-fetch latest version
agmd skill delete my-skill       # Remove from registry

# Registry git (runs git in ~/.agmd, from anywhere)
agmd git init
agmd git remote add origin <url>
agmd git add -A && agmd git commit -m "sync" && agmd git push
agmd git pull
agmd git status
agmd git log --oneline

# Local registry (project-scoped, team-shared via git)
agmd init --local                # Create .agmd/ in project root
agmd new rule:my-rule --local    # Create item in local registry (overrides global)
` + "```" + `

### Migration: Existing Projects

| Command | Use when | Result |
|---------|----------|--------|
` + "|" + ` ` + "`agmd migrate <file>`" + ` | Project has raw/unstructured AI instructions | Content → ` + "`directives.md`" + ` (wrap sections with ` + "`:::new`" + `, then promote) |
` + "|" + ` ` + "`agmd collect`" + ` | Project already uses agmd (has ` + "`directives.md`" + `) | Registry items → ` + "`~/.agmd/`" + ` for reuse |

Quick migration flow:
` + "```" + `bash
agmd migrate CLAUDE.md   # creates directives.md, opens editor
# wrap sections with :::new ... :::end in editor, then:
agmd promote --all       # saves :::new blocks to ~/.agmd/
agmd sync                # generates AGENTS.md
agmd symlink --target claude  # symlink AGENTS.md → CLAUDE.md (if needed)
` + "```" + `

The built-in ` + "`managing-agmd`" + ` skill provides detailed step-by-step guidance. Link it with:
` + "```" + `bash
agmd skill link managing-agmd
` + "```" + `

### Symlinking Output

agmd always generates ` + "`AGENTS.md`" + `. To use the output with tools that expect a different filename:

` + "```" + `bash
agmd symlink --target claude   # AGENTS.md → CLAUDE.md  (for Claude Code)
agmd symlink --target cursor   # AGENTS.md → .cursorrules (for Cursor)
agmd symlink --target windsurf # AGENTS.md → .windsurfrules (for Windsurf)
agmd symlink --list            # See all available targets
` + "```" + `

### Registry Resolution Order

When looking up items (e.g. ` + "`:::use rule:foo`" + `):

1. ` + "`.agmd/rule/foo.md`" + ` — project-local (committed to project git, team-shared)
2. ` + "`~/.agmd/rule/foo.md`" + ` — global (personal, synced via ` + "`agmd git`" + `)

### Personal Overrides

Create ` + "`directives.local.md`" + ` alongside ` + "`directives.md`" + ` for machine-specific or personal
directives that should not be committed. It is automatically appended to ` + "`directives.md`" + `
during ` + "`agmd sync`" + ` and is added to ` + "`.gitignore`" + ` by ` + "`agmd init`" + `.

### Reserved Types

Some types have special subcommands:

- ` + "`task`" + ` - Project tasks with dependencies, priority (P0-P4), type (bug/feature/task/chore)
- ` + "`file`" + ` - Raw files without frontmatter (` + "`agmd file ...`" + `)
- ` + "`doc`" + ` - Documentation folders, symlinked (` + "`agmd doc ...`" + `)
- ` + "`skill`" + ` - Agent Skills from GitHub (` + "`agmd skill ...`" + `)
- ` + "`profile`" + ` - Project templates (` + "`agmd init profile:name`" + `)

### Important

- Edit ` + "`directives.md`" + `, not ` + "`AGENTS.md`" + ` (it gets overwritten on sync)
- Run ` + "`agmd sync`" + ` after changes to regenerate AGENTS.md
- Use ` + "`:::new`" + ` for project-specific content, then ` + "`agmd promote`" + ` to reuse elsewhere
- Types are flexible: use rule, workflow, prompt, guide, or any custom type
- Reserved types (task, file, doc, skill) use their own subcommands, not generic commands
- Commit ` + "`.agmd/`" + ` to share project rules with teammates
- Create ` + "`directives.local.md`" + ` for personal/machine-specific directives (gitignored, merged at sync)
`
}
