package registry

// GetDefaultProfileTemplate returns the default profile template
func GetDefaultProfileTemplate() string {
	return `---
name: default
description: "Default directives.md template with basic structure"
---

# Agent Instructions

*Generated by agmd - <https://github.com/GluonGrid/agmd>*

## Rules

Add rules using: agmd add rule:NAME

## Workflows

Add workflows using: agmd add workflow:NAME

## Guidelines

Add guidelines using: agmd add guideline:NAME

## Custom Instructions

Add your project-specific instructions, setup notes, and context here.
This section is preserved when regenerating directives.md.
`
}

// GetMinimalProfileTemplate returns a minimal profile template (legacy)
func GetMinimalProfileTemplate() string {
	return GetDefaultProfileTemplate()
}

// GetDefaultDirectivesTemplate returns the default directives.md template (when no profile specified)
func GetDefaultDirectivesTemplate() string {
	return GetMinimalProfileTemplate()
}
