package registry

// GetDefaultProfileTemplate returns the default profile template
func GetDefaultProfileTemplate() string {
	return `---
name: default
description: "Default directives.md template with basic structure"
---

# Agent Instructions

*Generated by agmd - <https://github.com/GluonGrid/agmd>*

:::include guide:agmd

## Project Rules

## Workflows

## Custom Instructions

Add your project-specific instructions, setup notes, and context here.
`
}

// GetDefaultDirectivesTemplate returns the fallback template when no profile is found
func GetDefaultDirectivesTemplate() string {
	return GetDefaultProfileTemplate()
}

// GetAgmdGuideTemplate returns the agmd guide that teaches AI how to use agmd
func GetAgmdGuideTemplate() string {
	return `---
name: agmd
description: "Guide for AI assistants on how to use agmd directives"
---

## agmd Quick Reference

This project uses **agmd** to manage AI instructions. The source file is ` + "`directives.md`" + ` and it generates ` + "`AGENTS.md`" + `.

### Directive Syntax

` + "```" + `markdown
:::include type:name     # Include a single item from ~/.agmd/type/name.md
:::list type             # Include multiple items
item1
item2
:::end
:::new type:name         # Define inline content (promote to registry later)
content here...
:::end
` + "```" + `

### Commands for AI Assistants

` + "```" + `bash
# Read content (no editor)
agmd show type:name              # Display item content
agmd show type:name --raw        # Include frontmatter

# Create items (no editor)
agmd new type:name --no-editor
agmd new type:name --content "# Content here"
echo "Content" | agmd new type:name

# Update items (no editor)
agmd edit type:name --content "# New content"
echo "Content" | agmd edit type:name

# Other commands
agmd sync                        # Generate AGENTS.md from directives.md
agmd list                        # List all registry items
agmd promote --all               # Promote all :::new blocks to registry
` + "```" + `

### Important

- Edit ` + "`directives.md`" + `, not ` + "`AGENTS.md`" + ` (it gets overwritten on sync)
- Run ` + "`agmd sync`" + ` after changes to regenerate AGENTS.md
- Use ` + "`:::new`" + ` for project-specific content, then ` + "`agmd promote`" + ` to reuse elsewhere
- Types are flexible: use rule, workflow, prompt, guide, or any custom type
`
}
