package cmd

import (
	"fmt"
	"os"

	"agmd/pkg/registry"

	"github.com/fatih/color"
	"github.com/spf13/cobra"
)

var initCmd = &cobra.Command{
	Use:   "init",
	Short: "Initialize a new project with directives.md",
	Long: `Initialize a new project by creating directives.md (source file).

Creates directives.md with:
- A title and introduction
- Example sections showing :::list and :::include directives
- Instructions on how to use agmd

Run 'agmd generate' to create AGENTS.md from directives.md.

Examples:
  agmd init           # Initialize in current directory`,
	RunE: runInit,
}

func init() {
	rootCmd.AddCommand(initCmd)
}

func runInit(cmd *cobra.Command, args []string) error {
	green := color.New(color.FgGreen).SprintFunc()
	blue := color.New(color.FgBlue).SprintFunc()
	red := color.New(color.FgRed).SprintFunc()

	fmt.Printf("%s Initializing agmd project...\n", blue("→"))

	// Check if registry exists
	reg, err := registry.New()
	if err != nil {
		return fmt.Errorf("failed to load registry: %w", err)
	}

	if !reg.Exists() {
		return fmt.Errorf("registry not found at %s\n%s\nRun 'agmd setup' first to initialize the registry",
			red(reg.BasePath),
			red("✗"))
	}

	// Check if directives.md already exists
	if _, err := os.Stat(directivesMdFilename); err == nil {
		return fmt.Errorf("directives.md already exists in current directory")
	}

	// Create template directives.md with directive syntax
	fmt.Printf("%s Creating directives.md...\n", blue("→"))
	template := `# Agent Instructions

*Generated by agmd - <https://github.com/GluonGrid/agmd>*

## About

This file provides instructions and context for AI coding agents.

You can add rules, workflows, and guidelines using agmd directives:

- **Single include**: ` + "`:::include:TYPE name`" + ` - Include one item
- **Multiple includes**: ` + "`:::list:TYPE ... :::end`" + ` - Include a list of items
- **Inline content**: ` + "`:::new:TYPE name=value ... :::end`" + ` - Define content inline

## Rules

Add your project rules here. Examples:

` + "```markdown" + `
:::include:rule typescript
` + "```" + `

Or use a list:

` + "```markdown" + `
:::list:rules
typescript
eslint
security
:::end
` + "```" + `

## Workflows

Add your project workflows here:

` + "```markdown" + `
:::list:workflows
release
testing
:::end
` + "```" + `

## Custom Instructions

Add any project-specific instructions, setup guides, or notes below.
All non-directive content is preserved when running ` + "`agmd generate`" + `.

### Getting Started

To use this file:

1. Add rules with ` + "`agmd add rule <name>`" + `
2. Create custom rules with ` + "`agmd new rule <name>`" + `
3. Expand directives with ` + "`agmd generate`" + `
4. Edit this file directly to add your own content
`

	if err := os.WriteFile(directivesMdFilename, []byte(template), 0644); err != nil {
		return fmt.Errorf("failed to write directives.md: %w", err)
	}

	fmt.Printf("%s Created directives.md\n", green("✓"))

	fmt.Printf("\n%s Project initialized successfully!\n", green("✓"))
	fmt.Println("\nCreated:")
	fmt.Printf("  • %s - Source file with directives (edit this)\n", directivesMdFilename)

	fmt.Println("\nNext steps:")
	fmt.Println("  • Edit directives.md to add directives")
	fmt.Println("  • Run 'agmd add rule <name>' to add rules to directives.md")
	fmt.Println("  • Run 'agmd generate' to create AGENTS.md for AI agents")
	fmt.Println("  • Run 'agmd new rule <name>' to create custom rules")

	return nil
}
